- name: this play book is to install catalogue and run catalogue service.
  hosts: catalogue
  become: yes

  tasks:
    - name: installing nodejs script.
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: installing nodejs
      ansible.builtin.yum:
        name: nodejs
        state: installed
    
    - name: create roboshop user 
      ansible.builtin.shell: id roboshop
      register: out
      ignore_errors: true
    
    - name: print the output of roboshop user present or not
      ansible.builtin.debug: 
        msg: "{{out}}"

    - name : print he exit status of user roboshop
      ansible.builtin.debug:
        msg: "{{out.rc}}"
