- name: this playbook is used to install catalogue
  hosts: catalogue
  become: yes


  tasks:
    - name: run nodejs script to install setup nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: installing nodejs 
      ansible.builtin.yum:
        name: nodejs
        state: installed

    - name: checking roboshop user exists or not
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - name: printing the output of roboshop user 
      ansible.builtin.debug:
       msg: "{{out}}"

    - name: to print the exit status of roboshop user
      ansible.builtin.debug:
        msg: "{{out.rc}}"

    - name: creating a roboshop user
      ansible.builtin.user:
        user: roboshop
      when: out.rc != 0

    - name: condition to check /app directory is presnt or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: print the output  /app directory is presnt or not 
      ansible.builtin.debug: 
        msg: "{{directory}}"

    - name: print the output  /app directory is presnt or not 
      ansible.builtin.debug: 
        msg: "{{directory.stat.exists}}"

    - name: creating /app directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False

  