- name: this playbook is used to install catalogue
  hosts: catalogue
  become: yes


  tasks:
    - name: run nodejs script to install setup nodejs reop
      ansible.builtin.command: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: installing nodejs 
      ansible.builtin.yum:
        name: nodejs
        state: installed

    - name: creating a roboshop user
      ansible.builtin.shell: id roboshop
      