- name: this playbook is used to install mongodb
  hosts: mongodb
  become: yes

  tasks:
    - name: copy mondo.rep file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/

    - name: installing mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: starting mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: editing mongodb.conf file to change from 127.0.0.0. to 0.0.0.0
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    
    - name: restarting mongodb.
      ansible.builtin.service:
        name: mongod
        state: restarted
        

    

