- name: this playbook is to install mongodb db server
  hosts: mongodb
  become: yes

  tasks:
    - name: copying mongobd repo file from ansible sevver to mongodb server 
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/

    - name: installing mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed
    
    - name: starting mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true



