- name: this playbook is to install mongodb db server
  hosts: mongodb
  become: yes

  tasks:
    - name: copying mongobd repo file from ansible sevver to mongodb server 
      ansible.builtin.copy:
        src: mongo.reop
        dest: /etc/yum.repos.d/

        