- name: installing nginx
  hosts: web
  tasks:
    - name: insatll nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    